language: node_js

node_js:
  - "lts/*"

install: yarn

script: yarn lint

after_success: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: keplersj.com
  on:
    branch: master
